[data_paths]
parquet_files = ["data/devices.parquet"]

[spectrum_settings]
min_wavelength = 350
max_wavelength = 1000
step = 1

[filter_defaults]
center = 550.0
center_step = 50.0
width = 40.0
width_step = 5.0

[detector_defaults]
peak = 555.0
sensitivity = 1.0

[ui]
default_emitters = ["Thorlabs SLS701"]

[data_structure.emitters]
identifier_columns = ["company", "device_id"]
type_column = "type"
type_values = ["Lamp", "LED", "Laser", "Laser_Pumped_Phosphor"]
wavelength_keywords = ["wave_nm"]
intensity_keywords = ["int_au"]

[data_structure.filters]
identifier_columns = ["company", "device_id"]
type_column = "type"
wavelength_keywords = ["wave_nm"]
transmission_keywords = ["int_au"]

[data_structure.filters.type_keywords]
long_pass = ["long", "longpass", "long pass"]
short_pass = ["short", "shortpass", "short pass"]
band_pass = ["band", "bandpass", "band pass"]
safety_glasses = ["safety_glasses"]

[data_structure.detectors]
identifier_columns = ["company", "device_id"]
type_column = "type"
wavelength_keywords = ["wave_nm"]
sensitivity_keywords = ["int_au"]

[data_structure.detectors.type_keywords]
human_eye = ["si", "ge", "MCT HgCdTe", "uv si", "eye"]
